######################################################################
#
# File name : asyreset_Ttriger_tb.udo
# Created on: Mon Nov 25 20:46:38 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
