######################################################################
#
# File name : asyreset_Ttriger_tb_wave.do
# Created on: Mon Nov 25 20:46:38 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
